;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ido-switch-buffer
        isearch-repeat-forward
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-forward-regexp
        isearch-printing-char
        isearch-yank-word-or-char
        ))
